ANTHROPIC_API_KEY = "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"
DATABASE_URL = "postgresql://postgres.dfyscmcjtgrybivaxuuo:I3rKUgKPRtRSha6s@aws-1-us-east-1.pooler.supabase.com:5432/postgres"
APP_PASSWORD = "technicssl1400"
